version: '2'

services:
  bdb-driver:
    build:
      context: .
      dockerfile: ./compose/driver/Dockerfile
    volumes:
      - ./docs:/usr/src/app/docs
      - ./tests:/usr/src/app/tests
      - ./bigchaindb_driver:/usr/src/app/bigchaindb_driver
      - ./setup.py:/usr/src/app/setup.py
      - ./tox.ini:/usr/src/app/tox.ini
    environment:
      BDB_HOST: bdb-server
    command: pytest -v
  rdb:
    image: rethinkdb
    ports:
      - "58585:8080"
      - "28015"
  bdb-server:
    build: ./compose/server
    environment:
      BIGCHAINDB_DATABASE_HOST: rdb
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
    ports:
      - "9984"
    command: bigchaindb start
